config/routes.rb
Rails.application.routes.draw do
  # Глобальные API-маршруты (без локали)
  namespace :api do
    get "next_image", to: "api#next_image"
    get "prev_image", to: "api#prev_image"
    post "rate_image", to: "api#rate_image"
  end

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "work#index"

    # WorkController
    get "work", to: "work#index"
    get "choose_theme", to: "work#choose_theme"
    post "display_theme", to: "work#display_theme"
    get 'best_images', to: 'best_images#index'

    # Маршруты для аутентификации
    get 'signup', to: 'sessions#signup'
    post 'signup', to: 'sessions#create_user'
    get 'signin', to: 'sessions#new'
    post 'signin', to: 'sessions#create'
    delete 'signout', to: 'sessions#destroy'
    get 'profile', to: 'sessions#profile'

    # Остальные ресурсы
    resources :values, :themes, :images, :users

    # MainController
    get "main/index"
    get "main/help"
    get "main/contacts"
    get "main/about"
  end

  # Глобальный маршрут для переключения локали
  get 'toggle_locale', to: 'application#toggle_locale'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :values, dependent: :destroy

  before_create :create_remember_token

  validates :name,
            presence: true,  # Обязательное поле
            uniqueness: true,  # Уникальность имени
            length: { maximum: 50 }

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: URI::MailTo::EMAIL_REGEXP }

  validates :password, length: { minimum: 6 }, allow_nil: true

  # Метод для генерации нового токена
  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # Метод для шифрования токена
  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  # Создание токена перед сохранением пользователя
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_admin, only: %i[index show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.admin = params[:user][:admin] == "true" if current_user&.admin?
    respond_to do |format|
      if @user.save
        sign_in @user  # Автоматический вход после успешной регистрации
        format.html { redirect_to @user, notice: "Пользователь успешно создан." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if current_user&.admin?
        # Принимаем "true", "1", или "on" как истинное значение для admin
        admin_value = ["true", "1", "on"].include?(params[:user][:admin]&.downcase)
        if @user.update(user_params.merge(admin: admin_value))
          format.html { redirect_to @user, notice: "Пользователь успешно обновлен." }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to root_path, alert: "Доступ запрещён" }
        format.json { head :forbidden }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!
    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "Пользователь успешно удален." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])  # Исправлено с params.expect(:id)
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_admin
    redirect_to root_path, alert: 'Доступ запрещён' unless current_user&.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.slim
= form_with(model: user, html: { class: 'user-form' }) do |form|
  - if user.errors.any?
    .alert.alert-danger.mb-4
      h4.alert-heading = "#{pluralize(user.errors.count, "error")} prohibited this user from being saved:"
      ul.mb-0
        - user.errors.each do |error|
          li = error.full_message

  .form-group.mb-3
    = form.label :name, class: 'form-label'
    = form.text_field :name, class: 'form-control bg-dark text-light border-secondary'

  .form-group.mb-3
    = form.label :email, class: 'form-label'
    = form.email_field :email, class: 'form-control bg-dark text-light border-secondary'

  .form-group.mb-3
    = form.label :password, class: 'form-label'
    = form.password_field :password, class: 'form-control bg-dark text-light border-secondary'

  .form-group.mb-4
    = form.label :password_confirmation, class: 'form-label'
    = form.password_field :password_confirmation, class: 'form-control bg-dark text-light border-secondary'

  - if current_user&.admin?
    .form-group.mb-4
      = form.label :admin, 'Администратор'
      = form.check_box :admin

  .actions
    = form.submit class: 'btn btn-primary w-100'

app/views/users/_user.html.slim
div id="#{dom_id user}"
  p
    strong Name:
    =< user.name
  p
    strong Email:
    =< user.email

app/views/users/edit.html.slim
.container.py-5
  h1.mb-4.text-center Editing User
  == render "form", user: @user
  .mt-4.text-center
    = link_to @user, class: 'btn btn-info me-2' do
      i.fas.fa-eye
      |  Show User
    = link_to users_path, class: 'btn btn-outline-secondary' do
      i.fas.fa-arrow-left
      |  Back to users

app/views/users/index.html.slim
p style="color: green" = notice

h1.mb-4 Users

table.table.table-dark.table-striped.table-hover
  thead
    tr
      th ID
      th Name
      th Email
      th Actions

  tbody
    - @users.each do |user|
      tr
        td = user.id
        td = user.name
        td = user.email
        td
          = link_to "Show", user, class: 'btn btn-sm btn-info'
          = link_to "Edit", edit_user_path(user), class: 'btn btn-sm btn-warning mx-2'
          = link_to "Delete", user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

.mt-4
  = link_to "New User", new_user_path, class: 'btn btn-primary'

app/views/users/new.html.slim
.container.py-5
  h1.mb-4.text-center New User
  == render "form", user: @user
  .mt-4.text-center
    = link_to users_path, class: 'btn btn-outline-secondary' do
      i.fas.fa-arrow-left
      |  Back to users

app/views/users/show.html.slim
.container.py-5
  h1.mb-4.text-center Профиль пользователя
  .text-center.mb-4
    = gravatar_for(@user)
  p.text-success.text-center = notice
  table.table.table-dark.table-striped.mt-4
    thead
      tr
        th Поле
        th Значение
    tbody
      tr
        td ID
        td = @user.id
      tr
        td Имя
        td = @user.name
      tr
        td Email
        td = @user.email
      tr
        td Дата создания
        td = l(@user.created_at, format: :long)
  .mt-4.text-center
    = link_to "Редактировать", edit_user_path(@user), class: 'btn btn-secondary'
    = link_to "Назад к пользователям", users_path, class: 'btn btn-outline-light'
    = button_to "Удалить пользователя", @user, method: :delete, class: 'btn btn-danger mt-2'