config/routes.rb
Rails.application.routes.draw do
  # Глобальные API-маршруты (без локали)
  namespace :api do
    get "next_image", to: "api#next_image"
    get "prev_image", to: "api#prev_image"
    post "rate_image", to: "api#rate_image"
  end

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "work#index"

    # WorkController
    get "work", to: "work#index"
    get "choose_theme", to: "work#choose_theme"
    post "display_theme", to: "work#display_theme"
    get 'best_images', to: 'best_images#index'

    # Маршруты для аутентификации
    get 'signup', to: 'sessions#signup'
    post 'signup', to: 'sessions#create_user'
    get 'signin', to: 'sessions#new'
    post 'signin', to: 'sessions#create'
    delete 'signout', to: 'sessions#destroy'
    get 'profile', to: 'sessions#profile'

    # Остальные ресурсы
    resources :values, :themes, :images, :users

    # MainController
    get "main/index"
    get "main/help"
    get "main/contacts"
    get "main/about"
  end

  # Глобальный маршрут для переключения локали
  get 'toggle_locale', to: 'application#toggle_locale'
end

app/views/shared/_footer.html.slim
footer
  .container
    p © 2025 Expert Rater
    = link_to t('footer.about_us'), main_about_path(locale: I18n.locale)

app/views/shared/_header.html.slim
header
  .container
    nav
      ul
        li = link_to t('header.home'), root_path(locale: I18n.locale)
        li = link_to t('header.contacts'), main_contacts_path(locale: I18n.locale)
        li = link_to t('header.help'), main_help_path(locale: I18n.locale)
        li = link_to t('header.best'), best_images_path(locale: I18n.locale)
        - if current_user&.admin?
          li = link_to t('header.users'), users_path(locale: I18n.locale)
          li = link_to t('header.images'), images_path(locale: I18n.locale)
          li = link_to t('header.themes'), themes_path(locale: I18n.locale)
        li = link_to 'Rails Docs', 'https://rubyonrails.org', target: '_blank'
        - if signed_in?
          li.user-info
            = link_to profile_path(locale: I18n.locale), class: 'user-link' do
              = gravatar_for(current_user, size: 43)
        - else
          li = link_to t('header.sign_in'), signin_path(locale: I18n.locale)
          li = link_to t('header.sign_up'), signup_path(locale: I18n.locale)
        li.locale-switcher
          = link_to toggle_locale_path do
            = image_tag(flag_image, alt: t('header.language'), title: t('header.switch_language'), class: 'locale-flag')