config/routes.rb
Rails.application.routes.draw do
  # Глобальные API-маршруты (без локали)
  namespace :api do
    get "next_image", to: "api#next_image"
    get "prev_image", to: "api#prev_image"
    post "rate_image", to: "api#rate_image"
  end

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "work#index"

    # WorkController
    get "work", to: "work#index"
    get "choose_theme", to: "work#choose_theme"
    post "display_theme", to: "work#display_theme"
    get 'best_images', to: 'best_images#index'

    # Маршруты для аутентификации
    get 'signup', to: 'sessions#signup'
    post 'signup', to: 'sessions#create_user'
    get 'signin', to: 'sessions#new'
    post 'signin', to: 'sessions#create'
    delete 'signout', to: 'sessions#destroy'
    get 'profile', to: 'sessions#profile'

    # Остальные ресурсы
    resources :values, :themes, :images, :users

    # MainController
    get "main/index"
    get "main/help"
    get "main/contacts"
    get "main/about"
  end

  # Глобальный маршрут для переключения локали
  get 'toggle_locale', to: 'application#toggle_locale'
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :theme
  has_many :values, dependent: :destroy

  validates :name,
            presence: { message: "Название обязательно" },
            length: { maximum: 200 }

  validates :file,
            presence: { message: "Файл обязателен" }

  validates :ave_value,
            numericality: {
              allow_nil: true,
              greater_than_or_equal_to: 0,
              less_than_or_equal_to: 100
            }

  scope :popular, -> { where("ave_value > ?", 70) }
  delegate :name, to: :theme, prefix: true

  scope :theme_images, -> (theme_id) {
    select('id', 'name', 'file', 'ave_value')
      .where(theme_id: theme_id)
      .order(:id)
  }

  def next_in_theme
    self.class.where("id > ? AND theme_id = ?", id, theme_id)
        .order(:id)
        .first
  end

  def previous_in_theme
    self.class.where("id < ? AND theme_id = ?", id, theme_id)
        .order(id: :desc)
        .first
  end

  # Оставляем как вспомогательный метод
  def update_ave_value
    avg = values.average(:value)&.round(1)
    update_column(:ave_value, avg) unless avg.nil?
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]
  before_action :require_admin

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy!

    respond_to do |format|
      format.html { redirect_to images_path, status: :see_other, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.expect(image: [ :name, :file, :ave_value, :theme_id ])
    end

    def require_admin
      redirect_to root_path, alert: 'Доступ запрещён' unless current_user&.admin?
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.slim
= form_with(model: image) do |form|
  - if image.errors.any?
    div style="color: red"
      h2 = "#{pluralize(image.errors.count, "error")} prohibited this image from being saved:"
      ul
        - image.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.label :file, style: "display: block"
    = form.text_field :file

  div
    = form.label :ave_value, style: "display: block"
    = form.text_field :ave_value

  div
    = form.label :theme_id, style: "display: block"
    = form.text_field :theme_id

  div
    = form.submit

app/views/images/_image.html.slim
div id="#{dom_id image}"
  p
    strong Name:
    =< image.name
  p
    strong File:
    =< image.file
  p
    strong Ave value:
    =< image.ave_value
  p
    strong Theme:
    =< image.theme_id

app/views/images/edit.html.slim
h1 Editing image

== render "form", image: @image

br

div
  => link_to "Show this image", @image
  '|
  =< link_to "Back to images", images_path

app/views/images/index.html.slim
p style="color: green" = notice

h1 Listing images

table.table.table-dark.table-striped.table-hover.mt-4
  thead
    tr
      th Name
      th File
      th Theme
      th Ave value
      th[colspan="3"]

  tbody
    - @images.each do |image|
      tr
        td = image.name
        td = image.file
        td = image.theme.name
        td = image.ave_value
        td = link_to 'Show', image
        td = link_to 'Edit', edit_image_path(image)
        td = link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New Image', new_image_path, class: 'btn btn-primary mt-4'

app/views/images/new.html.slim
h1 New image

== render "form", image: @image

br

div
  = link_to "Back to images", images_path

app/views/images/show.html.slim
p style="color: green" = notice

== render @image

div
  .image-preview.mt-4
    = image_tag "pictures/#{@image.file}", class: 'img-custom', alt: @image.name

  => link_to "Edit this image", edit_image_path(@image)
  '|
  =< link_to "Back to images", images_path

  = button_to "Destroy this image", @image, method: :delete